# Generated by Django 5.1.5 on 2025-01-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('P', 'Percusión'), ('V', 'Viento'), ('A', 'Arco'), ('E', 'Electrónico'), ('T', 'Tecla'), ('C', 'Cuerda')], max_length=30)),
                ('picture', models.ImageField(null=True, upload_to='instrumento_image')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('S', 'Salida'), ('E', 'Entrada')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('instrumento_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyecto.inventario')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyecto.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyecto.cliente')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyecto.inventario')),
            ],
        ),
    ]
